### ISSUE TITLE
Is linux supported?

### ISSUE THREAD

**Issue by abose** [agmmnn/tauri-controls#2]
Greetings,

I recently discovered this library while porting the [Brackets.io](https://brackets.io/) project to Tauri. The UI of this library appears well-suited to our requirements.

Could you please confirm if this library supports Linux or have any plans to support linux?

Thank you in advance!

**Comment by agmmnn** [comment]
Hey, greetings.

Yes on linux systems default [`gnome` 44](https://release.gnome.org/44/) controls are shown (the last ones) the main idea of the library is to use the <window-controls> component once and show the native-looking controls of whatever os the app is run on.

In a future version I plan to copy designs of other linux DEs: `xde`, `budgie`. But it is not possible to detect DE with tauri ts api. Someone on discord said I can do it with [LinuxOSReleaseInfo](https://docs.rs/sys-info/latest/sys_info/struct.LinuxOSReleaseInfo.html) in [sys-info](https://crates.io/crates/sys-info) but the library is only typescript for now. idk maybe developers can be given a choice of controls to display in linux, like: `<WindowControls linuxDesktop={"gnome" | "kde" | "budgie"} />`

![chrome_DOXGfE9jtl](https://github.com/agmmnn/tauri-controls/assets/16024979/8975c7ce-8e33-4e72-bd3b-1954c24f8758)

*(note: automatic change of the order of the controls according to the system in the picture will come in the next version)*

**Comment by abose** [comment]
Thanks for the quick response and looks like Linux is supported then :)
Will update once we start integrating.
Closing as answered.
