### ISSUE TITLE
tauri-plugin-window is deprecated

### ISSUE THREAD

**Issue by dan-myles** [agmmnn/tauri-controls#22]
its been moved back to the main tauri api, cant use this package with tauri v2 beta

**Comment by liyasthomas** [comment]
any update on this? tauri-controls not working with tauri v2-beta.

**Comment by sdvina** [comment]
> any update on this? tauri-controls not working with tauri v2-beta.

see https://github.com/agmmnn/tauri-controls/pull/23   this pull request working with Tauri V2 Beta . Enjoy it  :)

**Comment by liyasthomas** [comment]
Yes, thanks for the PR.

**Comment by agmmnn** [comment]
Thank you so much @sdvina 🎉 

[v0.4.0](https://github.com/agmmnn/tauri-controls/releases/tag/v0.4.0)
