### ISSUE TITLE
What is the licence for this project

### ISSUE THREAD

**Issue by abose** [agmmnn/tauri-controls#3]
Hi, I couldn't find the license file in this repo.

**Comment by agmmnn** [comment]
Right, I added a note to the readme but not the file, I'll add it. I thought I'd make it MIT licensed. Is that suitable?

**Comment by abose** [comment]
Brackets/phcode is compatible with both MIT/GNU GPL licenses/ [most OSI-approved open source licences](https://opensource.org/licenses/).

**Comment by agmmnn** [comment]
https://github.com/agmmnn/tauri-controls/releases/tag/v0.0.5
