### ISSUE TITLE
Native looking setting tabs ui

### ISSUE THREAD

**Issue by Jarrodsz** [agmmnn/tauri-controls#4]
Great solution. 
would it be in the scope of the project to create a native looking settings window also?

something like 

![](https://i.stack.imgur.com/8TCrc.png)

im currently rebuilding this ui with tailwind css but its quite a challange to make it look native

**Comment by agmmnn** [comment]
Unfortunately this is beyond the purpose of this library, but you can follow the design prototypes below:

- [Apple Design Resources - macOS](https://www.figma.com/community/file/1251588934545918753) @apple
- [macOS Monterey UI Kit for Figma](https://www.figma.com/community/file/1034539431656086181/macOS-Monterey-UI-Kit-for-Figma) @joey
- [macOS Big Sur UI Kit for Figma](https://www.figma.com/community/file/877084038660699458) @joey
