### ISSUE TITLE
display of controls is different in macos/safari(13)

### ISSUE THREAD

**Issue by reyamir** [agmmnn/tauri-controls#5]
Hello,
Thank for great library
I'm trying integrate `WindowTitleBar` to my app, but it's look weird, maybe I use it wrong
<img width="553" alt="image" src="https://github.com/agmmnn/tauri-controls/assets/123083837/418b36cc-4d0d-46fb-aaf7-1d84353a4d30">

```jsx
<WindowTitlebar
          controlsOrder="platform"
          windowControlsProps={{ platform: 'macos' }}
        >
          <button
            type="button"
            onClick={() => goBack()}
            className="group inline-flex h-6 w-6 items-center justify-center rounded-md hover:bg-zinc-900"
          >
            <ArrowLeftIcon className="h-4 w-4 text-zinc-500 group-hover:text-zinc-300" />
          </button>
          <button
            type="button"
            onClick={() => goForward()}
            className="group inline-flex h-6 w-6 items-center justify-center rounded-md hover:bg-zinc-900"
          >
            <ArrowRightIcon className="h-4 w-4 text-zinc-500 group-hover:text-zinc-300" />
          </button>
        </WindowTitlebar>
```

**Comment by agmmnn** [comment]
Hello, Thanks! Is it the same when choosing other platforms windows, gnome?

**Comment by agmmnn** [comment]
You are right, chrome(116) and safari(13) behave differently, I will fix it right away.

![](https://github.com/agmmnn/tauri-controls/assets/16024979/4889a911-4572-46a3-a758-9d481d04e440)

**Comment by agmmnn** [comment]
Hey, can you try version `0.0.6`, it seems ok for me.

![](https://github.com/agmmnn/tauri-controls/assets/16024979/11adae6d-1b22-427c-b95b-e90045a5863a)

**Comment by reyamir** [comment]
yup, work fine now
